### ISSUE TITLE
good integration login & register

### ISSUE THREAD

**Issue by pacomski** [atelier-cartographique/waend#12]

**Comment by pacomski** [comment]
Register & login buttons always available when not logged-in & disabled when logged-in
Register button : launch register command in console, registration with command line
  - ask for email
  - ask for password
  - ask password confirmation + match = yes
  - auto-login

Login button : ask for user name in console, then ask for password

**Comment by crickxson** [comment]
With password hidden

**Comment by crickxson** [comment]
With the help accessible before login
