### ISSUE TITLE
lineDash style looks broken

### ISSUE THREAD

**Issue by pacomski** [atelier-cartographique/waend#46]

**Comment by pacomski** [comment]
still some cracks in there

**Comment by pacomski** [comment]
looks ok for lines, problems only with polygons
-> see "test import" map and "dash play" layer.

**Comment by pacomski** [comment]
it looks like it works everywhere except in Chrome (Chromium, Firefox, Safari are all ok..)

**Comment by pierremarc** [comment]
I close it then
