### ISSUE TITLE
delete layer

### ISSUE THREAD

**Issue by pacomski** [atelier-cartographique/waend#5]

**Comment by pacomski** [comment]
would be nice for june 18th

**Comment by pacomski** [comment]
so far the option is/will be to detach the layer from it's map. 
It goes then in wænd dark matter..

**Comment by pacomski** [comment]
... Either delete or detach would be very welcome ;)

**Comment by pacomski** [comment]
detach done
let's keep this open until a proper delete

**Comment by pierremarc** [comment]
detach will be enough for a while. we can even imagine having some cron job server side to properly delete unreachable layers. Or people would be happy to retrieve detached/deleted layers and we keep them in this dark area

closing for now, definitely not on the TODO at the moment
