### ISSUE TITLE
Open the help window

### ISSUE THREAD

**Issue by boisophieron** [atelier-cartographique/waend#57]
Ability to open the help window in another window or tab or block, to see map and help at the same time

**Comment by pierremarc** [comment]
Yep, it would be hackish to do it right in wænd but we might want to simply put a regular link somewhere to http://alpha.waend.com/documentation/help.html
The ```help``` command actually just opens this page in an iframe.

**Comment by pacomski** [comment]
link added on top of Help

**Comment by boisophieron** [comment]
Where? I'm blind.
