### ISSUE TITLE
"gg | edit | sg" returns error (we could use it to copy/paste features)

### ISSUE THREAD

**Issue by pacomski** [atelier-cartographique/waend#58]
TypeError: Cannot use 'in' operator to search for 'geometry' in {"_geometry":{"type":"LineString","coordinates":[[26.0829635052788,44.4208940365397],[26.083028918116,44.4203592245786]]}}

**Comment by pierremarc** [comment]
Well, ```sg``` is meant to handle Geometry instances. We could improve the command to handle more types of input, but to be honest, I do not see it as a priority. Except if you actually need it though.

**Comment by pacomski** [comment]
Ok, i thought it was working the same way as ```gg | trace | sg```, that would have been a good trick for copy/paste ;)
