### ISSUE TITLE
looks like we would need some navigation options on map editor

### ISSUE THREAD

**Issue by pacomski** [atelier-cartographique/waend#75]
Post workshop : many participants didn't get the "navigation mode", or found it not handy.
 
Maybe we can think about merging navigation and edition modes ; keeping in mind that map edition requires probably something more specific than a standard slippy map.

We only need to quit navigation when using tools (trace, draw etc.. ) to interact on the map. The rest of the time could be about easy navigation on the edited map. Helping wandering in editing mode could also activate a bit more the imagination, and the spreading of features around (hey, let's add an image here...then a short text there !). 
Without easy wandering, i think the publishing process could get a bit "screen sized", loosing the zoom idea and so on.

**Comment by pierremarc** [comment]
Merci Pacôme ! Super excitant de voir se dégager la plateforme à venir à
travers son usage.

--
pierre

**Comment by pacomski** [comment]
done :)
